version: '3.7'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'

  email:
    image: collabcode/training-email

  auth:
    build: .
    volumes:
      - .:/app
    ports:
      - '3001:${PORT}'
    environment:
      - NODE_ENV
    depends_on:
      - mongo
      - email
