version: '3.7'
services:
  auth:
    build: .
    ports:
      - '3001:${PORT}'
    environment:
      - NODE_ENV

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
